from oslo_config import cfg
from hpedockerplugin.hpe import fpg

hpe3par_opts = [
    cfg.StrOpt('hpe3par_api_url',
               default='',
               help="3PAR WSAPI Server Url like "
                    "https://<3par ip>:8080/api/v1",
               deprecated_name='hp3par_api_url'),
    cfg.StrOpt('hpe3par_username',
               default='',
               help="3PAR username with the 'edit' role",
               deprecated_name='hp3par_username'),
    cfg.StrOpt('hpe3par_password',
               default='',
               help="3PAR password for the user specified in hpe3par_username",
               secret=True,
               deprecated_name='hp3par_password'),
    cfg.ListOpt('hpe3par_cpg',
                default=["OpenStack"],
                help="List of the CPG(s) to use for volume creation",
                deprecated_name='hp3par_cpg'),
    cfg.ListOpt('hpe3par_snapcpg',
                default=[],
                help="List of the CPG(s) to use for snapshot creation",
                deprecated_name='hp3par_snapcpg'),
    cfg.BoolOpt('hpe3par_debug',
                default=False,
                help="Enable HTTP debugging to 3PAR",
                deprecated_name='hp3par_debug'),
    cfg.ListOpt('hpe3par_iscsi_ips',
                default=[],
                help="List of target iSCSI addresses to use.",
                deprecated_name='hp3par_iscsi_ips'),
    cfg.BoolOpt('hpe3par_iscsi_chap_enabled',
                default=False,
                help="Enable CHAP authentication for iSCSI connections.",
                deprecated_name='hp3par_iscsi_chap_enabled'),
    cfg.BoolOpt('suppress_requests_ssl_warnings',
                default=False,
                help='Suppress requests library SSL certificate warnings.'),
    cfg.DictOpt('replication_device',
                default={},
                help="Multi opt of dictionaries to represent a replication "
                     "target device.  This option may be specified multiple "
                     "times in a single config section to specify multiple "
                     "replication target devices.  Each entry takes the "
                     "standard dict config form: replication_device = "
                     "target_device_id:<required>,"
                     "key1:value1,key2:value2..."),
]

hpe3par_file_opts = [
    cfg.StrOpt('hpe3par_api_url',
               default='',
               help="3PAR WSAPI Server Url like "
                    "https://<3par ip>:8080/api/v1",
               deprecated_name='hp3par_api_url'),
    cfg.StrOpt('hpe3par_username',
               default='',
               help="3PAR username with the 'edit' role",
               deprecated_name='hp3par_username'),
    cfg.StrOpt('hpe3par_password',
               default='',
               help="3PAR password for the user specified in hpe3par_username",
               secret=True,
               deprecated_name='hp3par_password'),
    cfg.HostAddressOpt('hpe3par_san_ip',
                       help="IP address of SAN controller",
                       deprecated_name='hp3par_san_ip'),
    cfg.StrOpt('hpe3par_san_login',
               default='',
               help="Username for SAN controller",
               deprecated_name='hp3par_san_login'),
    cfg.StrOpt('hpe3par_san_password',
               default='',
               help="Password for SAN controller",
               secret=True,
               deprecated_name='hp3par_san_password'),
    cfg.PortOpt('hpe3par_san_ssh_port',
                default=22,
                help='SSH port to use with SAN',
                deprecated_name='hp3par_san_ssh_port'),
    cfg.MultiOpt('hpe3par_fpg',
                 item_type=fpg.FPG(),
                 help="The File Provisioning Group (FPG) to use",
                 deprecated_name='hp3par_fpg'),
    cfg.StrOpt('hpe3par_vfs',
               help="Name of virtual file server",
               deprecated_name='hp3par_vfs'),
    cfg.BoolOpt('hpe3par_fstore_per_share',
                default=False,
                help="Use one filestore per share",
                deprecated_name='hp3par_fstore_per_share'),
    cfg.BoolOpt('hpe3par_require_cifs_ip',
                default=False,
                help="Require IP access rules for CIFS (in addition to user)"),
    cfg.BoolOpt('hpe3par_debug',
                default=False,
                help="Enable HTTP debugging to 3PAR",
                deprecated_name='hp3par_debug'),
    cfg.StrOpt('hpe3par_cifs_admin_access_username',
               default='',
               help="File system admin user name for CIFS.",
               deprecated_name='hp3par_cifs_admin_access_username'),
    cfg.StrOpt('hpe3par_cifs_admin_access_password',
               default='',
               help="File system admin password for CIFS.",
               secret=True,
               deprecated_name='hp3par_cifs_admin_access_password'),
    cfg.StrOpt('hpe3par_cifs_admin_access_domain',
               default='LOCAL_CLUSTER',
               help="File system domain for the CIFS admin user.",
               deprecated_name='hp3par_cifs_admin_access_domain'),
    cfg.StrOpt('hpe3par_share_mount_path',
               default='/mnt/',
               help="The path where shares will be mounted when deleting "
                    "nested file trees.",
               deprecated_name='hpe3par_share_mount_path'),
]

san_opts = [
    cfg.StrOpt('san_ip',
               default='',
               help='IP address of SAN controller'),
    cfg.StrOpt('san_login',
               default='admin',
               help='Username for SAN controller'),
    cfg.StrOpt('san_password',
               default='',
               help='Password for SAN controller',
               secret=True),
    cfg.StrOpt('san_private_key',
               default='',
               help='Filename of private key to use for SSH authentication'),
    cfg.PortOpt('san_ssh_port',
                default=22,
                help='SSH port to use with SAN'),
    cfg.IntOpt('ssh_conn_timeout',
               default=30,
               help="SSH connection timeout in seconds"),
    cfg.IntOpt('timeout',
               default=10000,
               help=''),
]

volume_opts = [
    cfg.StrOpt('iscsi_ip_address',
               default='my_ip',
               help='The IP address that the iSCSI daemon is listening on'),
    cfg.PortOpt('iscsi_port',
                default=3260,
                help='The port that the iSCSI daemon is listening on'),
    cfg.BoolOpt('use_chap_auth',
                default=False,
                help='Option to enable/disable CHAP authentication for '
                     'targets.'),
    cfg.StrOpt('chap_username',
               default='',
               help='CHAP user name.'),
    cfg.StrOpt('chap_password',
               default='',
               help='Password for specified CHAP account name.',
               secret=True),
]
